# Generated by Django 4.0 on 2022-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_ogr2_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogr3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyad', models.CharField(max_length=50)),
                ('aciklama', models.TextField(max_length=50)),
                ('resim', models.FileField(blank=True, null=True, upload_to='kisiresmi/', verbose_name='Kişi resmi ekleyin')),
            ],
        ),
    ]
