# Generated by Django 3.2.12 on 2022-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Ürün Kodu'),
        ),
    ]
