# Generated by Django 3.2.12 on 2022-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_alter_urun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Ürün Kodu'),
        ),
    ]
