# Generated by Django 3.2.12 on 2022-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_alter_urun_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=50)),
                ('urun_fiyat', models.FloatField()),
                ('kategori', models.CharField(max_length=20, verbose_name='Kategori')),
                ('detay', models.TextField(verbose_name='Ürün Açıklaması')),
            ],
        ),
    ]
