# Generated by Django 3.2.12 on 2022-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0009_urunler3'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Ürün resmi ekleyin'),
        ),
    ]
